name: Pipe Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  schedule:
    - cron: "0 12 1,15 * *"

jobs:
  tests-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.6
          
      - name: Install dependencies
        run: bundle install

      - name: Running the tests
        run: bundle exec cucumber
